In [1]:
#mathematical and statistics
import numpy as np

In [2]:
x=np.array([10,9,7,10])
x.mean()

9.0

In [3]:
x.sum()

36

In [4]:
x.cumsum()

array([10, 19, 26, 36], dtype=int32)

In [5]:
x.cumprod()

array([  10,   90,  630, 6300], dtype=int32)

In [12]:
y=x>9
y

array([ True, False, False,  True])

In [13]:
y.sum()

2

In [14]:
y.any()

True

In [15]:
y.all()

False

In [17]:
x.sort()
x

array([ 7,  9, 10, 10])

In [18]:
np.unique(x)

array([ 7,  9, 10])

# multiple array save in file


In [22]:
#np.save(filename.npy,array)
#np.load(filename.npy)
#np.savez(file.npz, array1, array2)

x=[1,4,5,7]
y=[8,7,9]
np.save('testx.npy',x)
loadx=np.load('testx.npy')
loadx

array([1, 4, 5, 7])

In [25]:
np.savez('testxy.npz',x,y)

In [28]:
loadxy=np.load('testxy.npz')
loadxy.files

['arr_0', 'arr_1']

In [29]:
loadxy['arr_0']


array([1, 4, 5, 7])

In [30]:
x=np.random.randn(3,2)
y=np.random.randn(2,3)
x.dot(y)

array([[ 0.57895597, -1.25962325, -2.20096496],
       [ 0.55924332, -0.14674153,  3.15359914],
       [-0.25059076,  0.32326107, -0.14248266]])

In [35]:
x.transpose()

array([[-0.84688092, -0.52756555,  0.30630415],
       [-1.25327461,  1.09424879,  0.06437162]])

In [34]:
np.random.seed(7)