In [12]:
#multidimensional array 
l1 = np.arange(1,28).reshape((3,3,3))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Diminsion: 3
Type: int32
Size: 27
Itemsize: 4
Shape: (3, 3, 3)


In [2]:
import numpy as np

In [4]:
l1 = np.arange(1,13).reshape((12,1))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
Diminsion: 2
Type: int32
Size: 12
Itemsize: 4
Shape: (12, 1)


# Boolen Operation

In [13]:
a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [6]:
a % 3 == 0

array([[[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]],

       [[False, False,  True],
        [False, False,  True],
        [False, False,  True]]])

In [15]:
print(a)
a[a%3==0]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [8]:

print(a)
a[(a%3==0) & (a%5==0)]

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


array([15])

In [19]:
a=np.random.randn((10))

a


array([ 1.28530113, -0.29704814,  2.23713504,  1.14068184,  1.62476399,
       -0.15185877, -0.37316679,  0.20815456, -0.6523144 , -1.22722342])

In [20]:
b=np.random.randn((10))
b

array([ 1.17342574, -0.54865051,  0.52536768,  0.59771723, -0.69242605,
        1.23769058,  1.142219  , -0.53010838, -0.9000155 , -0.26182216])

In [21]:
a+b

array([ 2.45872688, -0.84569865,  2.76250273,  1.73839907,  0.93233793,
        1.08583181,  0.76905221, -0.32195382, -1.5523299 , -1.48904558])

In [22]:
a-b

array([ 0.11187539,  0.25160237,  1.71176736,  0.54296461,  2.31719004,
       -1.38954935, -1.51538578,  0.73826294,  0.2477011 , -0.96540126])

In [23]:
a*a

array([1.651999  , 0.0882376 , 5.00477321, 1.30115505, 2.63985801,
       0.02306109, 0.13925345, 0.04332832, 0.42551407, 1.50607732])

In [24]:
a*b

array([ 1.50820544,  0.16297562,  1.17531845,  0.68180519, -1.12502892,
       -0.18795417, -0.42623819, -0.11034448,  0.58709307,  0.32131429])

In [25]:
1/a

array([ 0.77802779, -3.36645768,  0.44700028,  0.87666864,  0.61547401,
       -6.58506587, -2.6797669 ,  4.80412248, -1.53300311, -0.81484755])

In [26]:
a>0

array([ True, False,  True,  True,  True, False, False,  True, False,
       False])

In [27]:
a[a>0]

array([1.28530113, 2.23713504, 1.14068184, 1.62476399, 0.20815456])

# indexing
#boolean indexing
#fancy indexing

In [28]:
x=np.array([1,7,8,4,3])

In [30]:
x[2]

8

In [31]:
x>5

array([False,  True,  True, False, False])

In [32]:
x[x>5]

array([7, 8])

In [33]:
y=np.random.randn(10,10)
y

array([[ 1.70215073, -0.25767136,  1.54684306, -0.36948989, -1.06181483,
        -1.25072811, -0.94733715,  1.73668383,  1.94626178, -0.5794571 ],
       [ 0.9599821 , -0.20099602, -0.00811604, -0.24913197, -0.44487732,
        -1.29994111,  1.29481508,  2.33003194, -1.242246  , -0.06738537],
       [ 0.45185771, -0.37223299, -0.54226171,  0.26301755, -1.6481743 ,
        -0.08649365,  0.18420607,  1.36030843, -0.76308266,  0.62473295],
       [ 0.71205852, -1.60048297,  0.05294458,  1.03149612, -0.70253522,
        -0.36453503, -0.95853718, -1.11951462,  1.06404683,  0.90859419],
       [ 1.74365938,  0.25977412,  0.07175515,  0.69707199,  0.24870773,
         0.04420915,  0.56538957,  2.36052461, -0.77034073, -0.59142985],
       [-0.61883853,  0.18785271, -0.3680114 ,  0.60639176,  0.03844184,
         0.09529269,  0.82296301,  0.38593394,  0.23432435,  0.0823166 ],
       [-1.01420692, -0.14484481,  2.2027395 , -0.80669815, -0.57699945,
        -0.25406849,  0.22575367, -1.12587344

In [35]:
y[0]

array([ 1.70215073, -0.25767136,  1.54684306, -0.36948989, -1.06181483,
       -1.25072811, -0.94733715,  1.73668383,  1.94626178, -0.5794571 ])

In [36]:
y[0][4]

-1.0618148295345142

In [37]:
y[2][3]

0.263017550297195

# fancy slicing

In [38]:
y[1:10:2] #odd rows

array([[ 0.9599821 , -0.20099602, -0.00811604, -0.24913197, -0.44487732,
        -1.29994111,  1.29481508,  2.33003194, -1.242246  , -0.06738537],
       [ 0.71205852, -1.60048297,  0.05294458,  1.03149612, -0.70253522,
        -0.36453503, -0.95853718, -1.11951462,  1.06404683,  0.90859419],
       [-0.61883853,  0.18785271, -0.3680114 ,  0.60639176,  0.03844184,
         0.09529269,  0.82296301,  0.38593394,  0.23432435,  0.0823166 ],
       [ 0.16554144,  0.61753304, -0.46492742,  0.83543483,  0.39422813,
        -0.23723809, -0.10691763, -0.45118677,  0.88351739,  0.53700881],
       [-1.12015337, -1.72122717,  1.16424602, -0.15885362, -0.81062635,
        -0.00379509,  0.77591626, -0.82738627, -0.01893427,  0.61327926]])

In [40]:
y[::,0:5]

array([[ 1.70215073, -0.25767136,  1.54684306, -0.36948989, -1.06181483],
       [ 0.9599821 , -0.20099602, -0.00811604, -0.24913197, -0.44487732],
       [ 0.45185771, -0.37223299, -0.54226171,  0.26301755, -1.6481743 ],
       [ 0.71205852, -1.60048297,  0.05294458,  1.03149612, -0.70253522],
       [ 1.74365938,  0.25977412,  0.07175515,  0.69707199,  0.24870773],
       [-0.61883853,  0.18785271, -0.3680114 ,  0.60639176,  0.03844184],
       [-1.01420692, -0.14484481,  2.2027395 , -0.80669815, -0.57699945],
       [ 0.16554144,  0.61753304, -0.46492742,  0.83543483,  0.39422813],
       [ 0.25623081, -0.72366991,  1.71859625, -1.60241687, -1.36987375],
       [-1.12015337, -1.72122717,  1.16424602, -0.15885362, -0.81062635]])

In [43]:
v=np.ones((5,5))
v

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [45]:
v[1:-1,1:-1]=0
v

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
v[[1,3,4],[1,3,1]] #shows rows and colums

array([0., 0., 1.])

In [47]:
w=np.random.randn(5,5)
w

array([[ 1.90217929e+00,  9.40923008e-01, -3.95714756e-01,
         1.17526787e+00,  1.46369414e+00],
       [-1.08320536e+00, -5.72227866e-01, -1.41911472e+00,
        -1.78109967e-02,  1.68256756e-01],
       [ 1.65404624e+00, -3.60056697e-01, -6.03217349e-01,
        -4.33616814e-01,  2.05548797e-01],
       [-4.84371416e-02,  1.05801471e+00,  4.92953074e-01,
         4.60656097e-02,  8.80846429e-01],
       [-2.91412315e-01,  1.60865458e-01, -1.20794963e-01,
        -5.83707855e-04, -2.56620553e+00]])

In [49]:
w[[1,3,4]]#shows rows

array([[-1.08320536e+00, -5.72227866e-01, -1.41911472e+00,
        -1.78109967e-02,  1.68256756e-01],
       [-4.84371416e-02,  1.05801471e+00,  4.92953074e-01,
         4.60656097e-02,  8.80846429e-01],
       [-2.91412315e-01,  1.60865458e-01, -1.20794963e-01,
        -5.83707855e-04, -2.56620553e+00]])

In [50]:
w[:,[1,3,4]] # shows colums 

array([[ 9.40923008e-01,  1.17526787e+00,  1.46369414e+00],
       [-5.72227866e-01, -1.78109967e-02,  1.68256756e-01],
       [-3.60056697e-01, -4.33616814e-01,  2.05548797e-01],
       [ 1.05801471e+00,  4.60656097e-02,  8.80846429e-01],
       [ 1.60865458e-01, -5.83707855e-04, -2.56620553e+00]])

# transposing arrays

In [51]:
w #5X5 ARRAY

array([[ 1.90217929e+00,  9.40923008e-01, -3.95714756e-01,
         1.17526787e+00,  1.46369414e+00],
       [-1.08320536e+00, -5.72227866e-01, -1.41911472e+00,
        -1.78109967e-02,  1.68256756e-01],
       [ 1.65404624e+00, -3.60056697e-01, -6.03217349e-01,
        -4.33616814e-01,  2.05548797e-01],
       [-4.84371416e-02,  1.05801471e+00,  4.92953074e-01,
         4.60656097e-02,  8.80846429e-01],
       [-2.91412315e-01,  1.60865458e-01, -1.20794963e-01,
        -5.83707855e-04, -2.56620553e+00]])

In [52]:
w.T

array([[ 1.90217929e+00, -1.08320536e+00,  1.65404624e+00,
        -4.84371416e-02, -2.91412315e-01],
       [ 9.40923008e-01, -5.72227866e-01, -3.60056697e-01,
         1.05801471e+00,  1.60865458e-01],
       [-3.95714756e-01, -1.41911472e+00, -6.03217349e-01,
         4.92953074e-01, -1.20794963e-01],
       [ 1.17526787e+00, -1.78109967e-02, -4.33616814e-01,
         4.60656097e-02, -5.83707855e-04],
       [ 1.46369414e+00,  1.68256756e-01,  2.05548797e-01,
         8.80846429e-01, -2.56620553e+00]])

In [56]:
r=np.array([[1,2,3],[2,3,4],[6,7,8]])
r

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8]])

In [57]:
r.T

array([[1, 2, 6],
       [2, 3, 7],
       [3, 4, 8]])

In [58]:
r.T.T

array([[1, 2, 3],
       [2, 3, 4],
       [6, 7, 8]])

In [59]:
r.T.T.T

array([[1, 2, 6],
       [2, 3, 7],
       [3, 4, 8]])