In [11]:
import numpy as np

# broadcasting


In [9]:
x=np.arange(1,26).reshape(5,5)

y=[[1],[2],[3],[4],[5]]

x


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [4]:
y

[[1], [2], [3], [4], [5]]

In [5]:
y=np.array(y)


In [6]:
y

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [7]:
x+y

array([[ 2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12],
       [14, 15, 16, 17, 18],
       [20, 21, 22, 23, 24],
       [26, 27, 28, 29, 30]])

In [8]:
x+[1,2,3,4,5]

array([[ 2,  4,  6,  8, 10],
       [ 7,  9, 11, 13, 15],
       [12, 14, 16, 18, 20],
       [17, 19, 21, 23, 25],
       [22, 24, 26, 28, 30]])

# tile and repeat concept

In [14]:
d=np.array([1,5,7,8])

In [15]:
np.repeat(d,3)

array([1, 1, 1, 5, 5, 5, 7, 7, 7, 8, 8, 8])

In [17]:
np.tile(d,3)

array([1, 5, 7, 8, 1, 5, 7, 8, 1, 5, 7, 8])