In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

In [18]:
x=np.zeros((4,4,4))
print(x)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [19]:
x.shape

(4, 4, 4)

In [25]:
y=x.reshape((32,2))

print(y)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [26]:
x=np.ones((10,10))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [30]:
y=x.reshape((2,5,2,5))
y

array([[[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]],


       [[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]]])

In [31]:
x=np.empty((5,5))

array([[3.00399061e-307, 8.06623226e-308, 4.67291993e-307,
        1.80371779e-312, 4.00536722e-307],
       [1.89144350e-307, 4.00545549e-307, 2.78147304e-307,
        4.00540456e-307, 3.11522733e-307],
       [2.33644299e-307, 3.44900708e-307, 1.05697374e-307,
        2.00265475e-307, 4.22792892e-307],
       [1.89144519e-307, 1.06807687e-306, 4.22792892e-307,
        4.00540457e-307, 3.11522733e-307],
       [1.44635488e-307, 9.34609111e-307, 1.06809792e-306,
        2.78149001e-307, 4.00538080e-307]])

In [32]:
x.dtype

dtype('float64')

In [39]:
z=np.arange(1,100,2)

In [42]:
y.ndim

4

In [44]:
l1=np.arange(1,13)
l1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
print("dimension", l1.ndim)

dimension 1


In [46]:
print("type", l1.dtype)

type int32


In [47]:
print("itemsize", l1.itemsize)

itemsize 4


In [51]:
#methods for reshape
a=np.array([[1,2,3],
            [4,5,6]])
a.shape= (3,2)
print (a)

[[1 2]
 [3 4]
 [5 6]]


In [53]:
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
a=np.arange(24)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [56]:
b=a.reshape(8,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [60]:
#generate random number
a=np.random.randn((10))

In [61]:
#remove negative sign
np.abs(a)

array([1.80118719, 0.08747601, 0.36193407, 0.3566357 , 0.15457364,
       0.67571348, 0.99597427, 0.09359671, 1.0400023 , 0.05213704])

In [71]:
c=np.array([7,8,-20,2])
np.abs(c)

array([ 7,  8, 20,  2])

In [62]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [73]:
d=c*5
d

array([  35,   40, -100,   10])

In [76]:
c=np.array([7,8,20,2])
np.sqrt(c)

array([2.64575131, 2.82842712, 4.47213595, 1.41421356])