In [3]:
#squareroot and power
x=np.array([10,9,5,4,2])
np.sqrt(x)

array([3.16227766, 3.        , 2.23606798, 2.        , 1.41421356])

In [2]:
import numpy as np

In [4]:
np.power(x,2)

array([100,  81,  25,  16,   4], dtype=int32)

In [6]:
y=np.array([7,1,2,3,-1])
np.maximum(x,y)

array([10,  9,  5,  4,  2])

In [7]:
np.max(x)

10

In [8]:
np.min(x)

2

# np.where

In [10]:
salary=np.array([0,-1,10000,50000])
np.where(salary<=0, 25000, salary)

array([25000, 25000, 10000, 50000])

In [11]:
np.where(salary<=0, 'not ok','ok')

array(['not ok', 'not ok', 'ok', 'ok'], dtype='<U6')