In [1]:
#reshape
import numpy as np

In [2]:
x=np.random.randn(4,5)
x

array([[ 0.82552283, -1.34106904, -0.74448323, -1.83416021,  0.72205712],
       [ 0.95124455, -0.70406718, -1.03752116, -0.29290845,  1.13676905],
       [ 0.71426104, -0.010625  , -0.68288555, -0.98137294, -0.50094246],
       [ 0.9584138 , -0.34123861,  0.76278781,  0.07794362, -0.01632332]])

In [4]:
x.reshape((2,2,5))

array([[[ 0.82552283, -1.34106904, -0.74448323, -1.83416021,
          0.72205712],
        [ 0.95124455, -0.70406718, -1.03752116, -0.29290845,
          1.13676905]],

       [[ 0.71426104, -0.010625  , -0.68288555, -0.98137294,
         -0.50094246],
        [ 0.9584138 , -0.34123861,  0.76278781,  0.07794362,
         -0.01632332]]])

In [5]:
x.reshape((2,2,-1))

array([[[ 0.82552283, -1.34106904, -0.74448323, -1.83416021,
          0.72205712],
        [ 0.95124455, -0.70406718, -1.03752116, -0.29290845,
          1.13676905]],

       [[ 0.71426104, -0.010625  , -0.68288555, -0.98137294,
         -0.50094246],
        [ 0.9584138 , -0.34123861,  0.76278781,  0.07794362,
         -0.01632332]]])

In [6]:
x.ravel()

array([ 0.82552283, -1.34106904, -0.74448323, -1.83416021,  0.72205712,
        0.95124455, -0.70406718, -1.03752116, -0.29290845,  1.13676905,
        0.71426104, -0.010625  , -0.68288555, -0.98137294, -0.50094246,
        0.9584138 , -0.34123861,  0.76278781,  0.07794362, -0.01632332])

In [7]:
x.flatten()

array([ 0.82552283, -1.34106904, -0.74448323, -1.83416021,  0.72205712,
        0.95124455, -0.70406718, -1.03752116, -0.29290845,  1.13676905,
        0.71426104, -0.010625  , -0.68288555, -0.98137294, -0.50094246,
        0.9584138 , -0.34123861,  0.76278781,  0.07794362, -0.01632332])

# concatenate

In [8]:
x=[[1,3,5],[7,9,0]]
ar1=np.array(x)
ar1

array([[1, 3, 5],
       [7, 9, 0]])

In [9]:
y=[[22,11,14],[2,4,8]]
ar2=np.array(y)
np.concatenate((ar1,ar2), axis=0)

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [22, 11, 14],
       [ 2,  4,  8]])

In [10]:
np.concatenate((ar1,ar2), axis=1)

array([[ 1,  3,  5, 22, 11, 14],
       [ 7,  9,  0,  2,  4,  8]])

In [11]:
np.vstack((ar1,ar2))

array([[ 1,  3,  5],
       [ 7,  9,  0],
       [22, 11, 14],
       [ 2,  4,  8]])

In [12]:
np.hstack((ar1,ar2))

array([[ 1,  3,  5, 22, 11, 14],
       [ 7,  9,  0,  2,  4,  8]])

In [13]:
#imp fancy slicing
v=np.arange(0,25).reshape((5,5))
v


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
v[[0,1,2]    ,   [1,3,2]]


array([ 1,  8, 12])

In [15]:
#v[[row_indexes], [col_indexes]]
v[v%3==0]



array([ 0,  3,  6,  9, 12, 15, 18, 21, 24])

In [16]:
     0  ([[1., 1., 1., 1., 1.], -5
     1  [1., 1., 1., 1., 1.],   -4
     2  [1., 1., 1., 1., 1.],   -3
     3  [1., 1., 1., 1., 1.],   -2
     4  [1., 1., 1., 1., 1.]])  -1


SyntaxError: invalid syntax (<ipython-input-16-f77dc87388a1>, line 2)

In [22]:
v=np.arange(1,26).reshape((5,5))
v
a=[1,2,3,4]


In [19]:
type(a)
a[1]='a'
a


[1, 'a', 3, 4]

# ye saad bhai ki ghalti hy


In [23]:
type(a)
v.dtype
v[1:-1,1:-1]='a'
v


ValueError: invalid literal for int() with base 10: 'a'